#!/bin/python

from sys import argv
from re import search
from os import environ

def main():
    if len(argv) < 3:
        print("Error: Expected file and title arguments")
        exit(1)

    file = argv[1]
    title = argv[2]
    date = ""

    with open(file, "r") as f:
        contents = f.read()
        date = search("\w\w\w \d\d, \d\d\d\d", contents).group()


    new_post = [
        "  <li>\n",
        "    <span class=\"list__title--small\">\n",
        "      <a href=\"./blogs/{FILE}\">{TITLE}</a>\n".format(FILE=file, TITLE=title),
        "      <time class=\"pull-right hidden-tablet\">{DATE}</time>\n".format(DATE=date),
        "    </span>\n",
        "  </li>\n",
    ]

    with open(environ['HOME'] + "/Dev/Web/barrolskii.github.io/blogindex.html", "r+") as f:
        contents = f.readlines()

        for i in range(len(contents)):
            if '<ul class="posts">' in contents[i]:
                i += 1
                for j in range(len(new_post)):
                    contents.insert(i + j, new_post[j])
                break

        f.seek(0, 0)
        f.write("".join(contents))

if __name__ == '__main__':
    main()
