#!/bin/sh

check_repo_commits()
{
	REPO_STATUS=$(git -C $1 status --porcelain)
	RESET='\033[0m'
	GREEN='\033[0;32m'
	RED='\033[0;31m'

	if [ -z "$REPO_STATUS" ]
	then
		echo -e "${GREEN}${1} can be synced. Syncing now...${RESET}"
		git -C $1 pull
		echo -e "\n"
	else
		echo -e "${RED}Unable to sync: ${1}"
		echo -e "Changes must be commited or added${RESET}"
		echo -e "\n"
	fi
}

for dir in $(find ~/Dev/ -maxdepth 2 -type d); do

	# Check if the current dir is a git repo
	[ -d "$dir/.git" ] && check_repo_commits $dir



done

