#!/bin/sh

if [ -z $1 ]; then
	grep --color -nTR --exclude-dir={.git,craftinginterpreters,imgui,Scripts,doom} "TODO" $1
else
	grep --color -n -T -R --exclude-dir={.git,craftinginterpreters,imgui,Scripts,doom} "TODO" ${HOME}/Dev/

fi

